services:
  app:
    image: ${DOCKER_USERNAME}/solusi-kemenag-frontend:latest
    container_name: kemenag-frontend
    restart: unless-stopped
    ports:
      - "${PORT:-4321}:4321"
    environment:
      - NODE_ENV=production
      - BACKEND_URL=${BACKEND_URL}
