services:
  frontend:
    image: solusi-kemenag-frontend:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4321:4321"
    environment:
      - HOST=0.0.0.0
      - PORT=4321
      - NODE_ENV=production
      - BACKEND_URL=${BACKEND_URL}
    restart: unless-stopped
    networks:
      - kemenag-net

networks:
  kemenag-net:
    driver: bridge
